---

variables:
  CORES: 2

debian:10--gcc:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-gcc-8-17
  script: 
    - . /duneci/bin/duneci-init-job
    - duneci-standard-test

debian:10--clang:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-clang-7-libcpp-17
  script:
  - . /duneci/bin/duneci-init-job
  - duneci-standard-test
