---

variables:
  CORES: 2

debian:12--gcc:
  image: registry.dune-project.org/docker/ci/debian:12
  script: 
    - . /duneci/bin/duneci-init-job
    - duneci-standard-test

debian:12--clang:
  image: registry.dune-project.org/docker/ci/debian:12
  script:
  - . /duneci/bin/duneci-init-job
  - duneci-standard-test
