---

before_script:
  - echo 'CMAKE_FLAGS+=" -DDUNE_PYTHON_VIRTUALENV_SETUP=1 -DDUNE_PYTHON_VIRTUALENV_PATH=/duneci/modules/dune-python-venv"' >> /duneci/cmake-flags/enable_virtualenv
  - echo 'CMAKE_FLAGS+="-DDUNE_PYTHON_ADDITIONAL_PIP_PARAMS=--extra-index-url https://gitlab.dune-project.org/api/v4/projects/1007/packages/pypi/simple"' >> /duneci/cmake-flags/pypi-mirror

variables:
  CORES: 2

debian:10--gcc:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-gcc-8-17
  script: duneci-standard-test

debian:10--clang:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-clang-7-libcpp-17
  script: duneci-standard-test
