#!/bin/bash

# It is recommended to install this hook when developing dune-testtools.
# It will run the python test suite on any push attempt.
# Type the following to do so:
#   cp git-pre-push ./.git/hooks/pre-push
# If it does not work make sure to install pytest (debian: python-pytest)
CHANGE_IN_PYTHON_DIR="diff --git a/python/"
git diff origin.. | if grep --quiet "$CHANGE_IN_PYTHON_DIR"
then
  echo "Run testsuite with python executable"
  env PYTHONPATH=$PYTHONPATH:. python -m pytest python/
  echo "Run testsuite with python3 executable"
  env PYTHONPATH=$PYTHONPATH:. python3 -m pytest python/
  exit $?
fi
