#!/bin/bash

# It is recommended to install this hook when developing dune-testtools.
# It will run the python test suite on any push attempt.
# Type the following to do so:
#   cp git-pre-push ./.git/hooks/pre-push
# If it does not work make sure to install pytest (debian: python-pytest)
CHANGE_IN_PYTHON_DIR="diff --git a/python/"
git diff origin.. | if grep --quiet "$CHANGE_IN_PYTHON_DIR"
then
  cd python
  rm dune_testtools/*.pyc && rm dune_testtools/wrapper/*.pyc && rm tests/*.pyc
  echo "Run testsuite with python executable"
  python -m pytest tests
  if [ $? -ne 0 ]
  then
    exit $?
  fi
  echo "Run testsuite with python3 executable"
  python3 -m pytest tests
  if [ $? -ne 0 ]
  then
    exit $?
  fi
  echo "Checking for PEP8 compliance"
  pyhton -m pytest --pep8
  exit $?
fi
